/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain;

import Base.ConexionBD;
import bean.ComputadoraBean;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author oscar
 */
public class Leer extends javax.swing.JInternalFrame {
    ConexionBD con=new ConexionBD("compu");

    /**
     * Creates new form Leer
     */
    public Leer() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        btnTodos = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Buscar:");

        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "No. de Serie", "Marca", "Modelo", "Disco Duro", "Ram", "Procesador", "Estado"
            }
        ));
        jScrollPane1.setViewportView(datatable);

        btnTodos.setText("Buscar todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar registro");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(btnLimpiar)
                        .addGap(148, 148, 148)
                        .addComponent(btnTodos)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTodos)
                    .addComponent(btnLimpiar))
                .addGap(123, 123, 123))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String serie; //Se declaran las variables.
        String enunciadoSQL;
        
        serie= txtBuscar.getText().toUpperCase().trim(); //se otiene el texto.
        //enunciadoSQL="SELECT * FROM tecno WHERE noSerie='"+serie+"'";//el enunciado de la accion en la BD.
        
        //con.consultar(enunciadoSQL);//Se realiza la accion.
           ConexionBD bD = new ConexionBD("compu");
        List<ComputadoraBean> list = bD.consultar("SELECT * FROM tecno WHERE noSerie='"+serie+"'");
        if(list != null){
            for (int i =0; i<list.size(); i++){
                ComputadoraBean bean = list.get(i);
                 datatable.getModel().setValueAt(bean.getNoSerie(),i, 0);
                 datatable.getModel().setValueAt(bean.getMarca(),i, 1);
                 datatable.getModel().setValueAt(bean.getModelo(),i, 2);
                 datatable.getModel().setValueAt(bean.getDisco(),i, 3);
                 datatable.getModel().setValueAt(bean.getRam(),i, 4);
                 datatable.getModel().setValueAt(bean.getProcesador(),i, 5);
                 datatable.getModel().setValueAt(bean.getEstado(),i, 6);
            }
                
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        // TODO add your handling code here:
        String serie; //Se declaran las variables.
        //String enunciadoSQL;
        
        serie= txtBuscar.getText().toUpperCase().trim(); //se otiene el texto.
        //enunciadoSQL="SELECT * FROM tecno WHERE noSerie='"+serie+"'";//el enunciado de la accion en la BD.
        //con.consultar(enunciadoSQL);//Se realiza la accion.
        
           ConexionBD bD = new ConexionBD("compu");
        List<ComputadoraBean> list = bD.consultar("SELECT * FROM tecno");
        if(list != null){
            for (int i =0; i<list.size(); i++){
                ComputadoraBean bean = list.get(i);
                 datatable.getModel().setValueAt(bean.getNoSerie(),i, 0);
                 datatable.getModel().setValueAt(bean.getMarca(),i, 1);
                 datatable.getModel().setValueAt(bean.getModelo(),i, 2);
                 datatable.getModel().setValueAt(bean.getDisco(),i, 3);
                 datatable.getModel().setValueAt(bean.getRam(),i, 4);
                 datatable.getModel().setValueAt(bean.getProcesador(),i, 5);
                 datatable.getModel().setValueAt(bean.getEstado(),i, 6);
            }
                
        }
    }//GEN-LAST:event_btnTodosActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
           txtBuscar.setText("");
           
             for (int i =0; i<datatable.getRowCount(); i++){
                 datatable.getModel().setValueAt(null,i, 0);
                 datatable.getModel().setValueAt(null,i, 1);
                 datatable.getModel().setValueAt(null,i, 2);
                 datatable.getModel().setValueAt(null,i, 3);
                 datatable.getModel().setValueAt(null,i, 4);
                 datatable.getModel().setValueAt(null,i, 5);
                 datatable.getModel().setValueAt(null,i, 6);
            }
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnTodos;
    private javax.swing.JTable datatable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
