/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package domain;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author oscar
 */
public class Puzzle extends javax.swing.JInternalFrame {
    
    boolean suspendido = false;
    int seg, min, hora, deci, con;
    private JLabel[] tablero = new JLabel[16];
    private int[] datos = new int[16];
    private int pos1;
    private int pos2;
    private boolean banClick;
    private int tipo;       //0= Libre , 1=Tradicional
    private int disponible; //Casilla vacia en tipo tradicional
    private JLabel lblTablero = new JLabel();
    private boolean banInicio;  //True=Ya inicio el juego,     False=Aún no inicia el juego
    private String nuevo;

    /**
     * Creates new form Puzzle
     */
    public Puzzle() {
        initComponents();
        seg = 0;
        min = 0;
        hora = 0;
        deci = 0;
        con = 1;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblImagen03 = new javax.swing.JLabel();
        lblImagen01 = new javax.swing.JLabel();
        lblImagen04 = new javax.swing.JLabel();
        lblImagen02 = new javax.swing.JLabel();
        lblImagen08 = new javax.swing.JLabel();
        lblImagen07 = new javax.swing.JLabel();
        lblImagen06 = new javax.swing.JLabel();
        lblImagen05 = new javax.swing.JLabel();
        lblImagen12 = new javax.swing.JLabel();
        lblImagen11 = new javax.swing.JLabel();
        lblImagen10 = new javax.swing.JLabel();
        lblImagen09 = new javax.swing.JLabel();
        lblImagen16 = new javax.swing.JLabel();
        lblImagen15 = new javax.swing.JLabel();
        lblImagen14 = new javax.swing.JLabel();
        lblImagen13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        cmbImagenes = new javax.swing.JComboBox<>();
        btnIniciar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        lblCompleto = new javax.swing.JLabel();
        lbltiempo = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
        });

        lblImagen03.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a3.jpg")); // NOI18N
        lblImagen03.setText("jLabel1");
        lblImagen03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen03MouseClicked(evt);
            }
        });

        lblImagen01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        lblImagen01.setText("jLabel1");
        lblImagen01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen01MouseClicked(evt);
            }
        });

        lblImagen04.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a4.jpg")); // NOI18N
        lblImagen04.setText("jLabel1");
        lblImagen04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen04MouseClicked(evt);
            }
        });

        lblImagen02.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a2.jpg")); // NOI18N
        lblImagen02.setText("jLabel1");
        lblImagen02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen02MouseClicked(evt);
            }
        });

        lblImagen08.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a8.jpg")); // NOI18N
        lblImagen08.setText("jLabel1");
        lblImagen08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen08MouseClicked(evt);
            }
        });

        lblImagen07.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a7.jpg")); // NOI18N
        lblImagen07.setText("jLabel1");
        lblImagen07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen07MouseClicked(evt);
            }
        });

        lblImagen06.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a6.jpg")); // NOI18N
        lblImagen06.setText("jLabel1");
        lblImagen06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen06MouseClicked(evt);
            }
        });

        lblImagen05.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a5.jpg")); // NOI18N
        lblImagen05.setText("jLabel1");
        lblImagen05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen05MouseClicked(evt);
            }
        });

        lblImagen12.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a12.jpg")); // NOI18N
        lblImagen12.setText("jLabel1");
        lblImagen12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen12MouseClicked(evt);
            }
        });

        lblImagen11.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a11.jpg")); // NOI18N
        lblImagen11.setText("jLabel1");
        lblImagen11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen11MouseClicked(evt);
            }
        });

        lblImagen10.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a10.jpg")); // NOI18N
        lblImagen10.setText("jLabel1");
        lblImagen10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen10MouseClicked(evt);
            }
        });

        lblImagen09.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a9_1.jpg")); // NOI18N
        lblImagen09.setText("jLabel1");
        lblImagen09.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen09MouseClicked(evt);
            }
        });

        lblImagen16.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a16.jpg")); // NOI18N
        lblImagen16.setText("jLabel1");
        lblImagen16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen16MouseClicked(evt);
            }
        });

        lblImagen15.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a15.jpg")); // NOI18N
        lblImagen15.setText("jLabel1");
        lblImagen15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen15MouseClicked(evt);
            }
        });

        lblImagen14.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a14.jpg")); // NOI18N
        lblImagen14.setText("jLabel1");
        lblImagen14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen14MouseClicked(evt);
            }
        });

        lblImagen13.setIcon(new javax.swing.ImageIcon("C:\\Users\\oscar\\OneDrive\\Documentos\\NetBeansProjects\\Inventario\\src\\imagenes\\a13.jpg")); // NOI18N
        lblImagen13.setText("jLabel1");
        lblImagen13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblImagen13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen01, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen02, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen03, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen04, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen05, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen06, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen07, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen08, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen09, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen10, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen11, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagen13, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen14, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen15, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblImagen16, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen04)
                    .addComponent(lblImagen01)
                    .addComponent(lblImagen03)
                    .addComponent(lblImagen02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen08)
                    .addComponent(lblImagen05)
                    .addComponent(lblImagen07)
                    .addComponent(lblImagen06))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen12)
                    .addComponent(lblImagen09)
                    .addComponent(lblImagen11)
                    .addComponent(lblImagen10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblImagen16)
                    .addComponent(lblImagen13)
                    .addComponent(lblImagen15)
                    .addComponent(lblImagen14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Imágenes:");

        cmbImagenes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbImagenes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android", "Mario Bros", "Sombrerero", "Payaso", "Favorita", "Numeros" }));
        cmbImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImagenesActionPerformed(evt);
            }
        });

        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tipo:");

        cmbTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libre ", "Tradicional" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        lblCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/android.jpg"))); // NOI18N
        lblCompleto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        lbltiempo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbltiempo.setText("00:00:00:00");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tiempo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblCompleto)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbImagenes, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCompleto)
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lbltiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbImagenes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(btnIniciar)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblImagen03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen03MouseClicked
        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImagen03MouseClicked

    private void lblImagen01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen01MouseClicked
        // TODO add your handling code here:
        tirar(0);
    }//GEN-LAST:event_lblImagen01MouseClicked

    private void lblImagen04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen04MouseClicked
        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImagen04MouseClicked

    private void lblImagen02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen02MouseClicked
        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImagen02MouseClicked

    private void lblImagen08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen08MouseClicked
        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImagen08MouseClicked

    private void lblImagen07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen07MouseClicked
        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImagen07MouseClicked

    private void lblImagen06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen06MouseClicked
        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImagen06MouseClicked

    private void lblImagen05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen05MouseClicked
        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImagen05MouseClicked

    private void lblImagen12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen12MouseClicked
        // TODO add your handling code here:
        tirar(11);
    }//GEN-LAST:event_lblImagen12MouseClicked

    private void lblImagen11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen11MouseClicked
        // TODO add your handling code here:
        tirar(10);
    }//GEN-LAST:event_lblImagen11MouseClicked

    private void lblImagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen10MouseClicked
        // TODO add your handling code here:
        tirar(9);
    }//GEN-LAST:event_lblImagen10MouseClicked

    private void lblImagen09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen09MouseClicked
        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImagen09MouseClicked

    private void lblImagen16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen16MouseClicked
        // TODO add your handling code here:
        tirar(15);
    }//GEN-LAST:event_lblImagen16MouseClicked

    private void lblImagen15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen15MouseClicked
        // TODO add your handling code here:
        tirar(14);
    }//GEN-LAST:event_lblImagen15MouseClicked

    private void lblImagen14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen14MouseClicked
        // TODO add your handling code here:
        tirar(13);
    }//GEN-LAST:event_lblImagen14MouseClicked

    private void lblImagen13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen13MouseClicked
        // TODO add your handling code here:
        tirar(12);
    }//GEN-LAST:event_lblImagen13MouseClicked

    private void cmbImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImagenesActionPerformed
        // TODO add your handling code here:
        banInicio = false;        //Requiere mezclarse para iniciar
        disponible = 15;
        //Se recetean los datos
        for (int i = 0; i < 16; i++) {
            datos[i] = 1;
        }
        //Poniendo bordes a las piezas del tablero
        for (int i = 0; i < 16; i++) {
            tablero[i].setBorder(new LineBorder(Color.black, 1));
        }
        int op;
        op = cmbImagenes.getSelectedIndex();
        if (!suspendido) {
            hilo.start();
            suspendido = true;
        } else {
            hilo.resume();
        }
        switch (op) {
            case 0:
            /**
            * Detiene el tiempo cada vez que se cambia de categoría.
            */
            hilo.suspend();
            suspendido = true;
            String nuevo = con + ".     " + lbltiempo.getText();
            con++;
            suspendido = true;
            seg = 0;
            min = 0;
            hora = 0;
            deci = 0;
            con = 1;
            lbltiempo.setText("00:00:00:00");
            lblCompleto.setIcon(new ImageIcon(getClass().getResource("/imagenes/android.jpg")));
            tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/a1.jpg")));
            tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/a2.jpg")));
            tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/a3.jpg")));
            tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/a4.jpg")));
            tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/a5.jpg")));
            tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/a6.jpg")));
            tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/a7.jpg")));
            tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/a8.jpg")));
            tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/a9.jpg")));
            tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/a10.jpg")));
            tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/a11.jpg")));
            tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/a12.jpg")));
            tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/a13.jpg")));
            tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/a14.jpg")));
            tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/a15.jpg")));
            if (tipo == 0) {
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/a16.jpg")));
            } else {
                lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            }
            break;
            case 1:
            hilo.suspend();
            suspendido = true;
            con++;
            suspendido = true;
            seg = 0;
            min = 0;
            hora = 0;
            deci = 0;
            con = 1;
            lbltiempo.setText("00:00:00:00");
            lblCompleto.setIcon(new ImageIcon(getClass().getResource("/imagenes/mario.png")));
            tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/m1.jpg")));
            tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/m2.jpg")));
            tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/m3.jpg")));
            tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/m4.jpg")));
            tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/m5.jpg")));
            tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/m6.jpg")));
            tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/m7.jpg")));
            tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/m8.jpg")));
            tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/m9.jpg")));
            tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/m10.jpg")));
            tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/m11.jpg")));
            tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/m12.jpg")));
            tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/m13.jpg")));
            tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/m14.jpg")));
            tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/m15.jpg")));
            if (tipo == 0) {
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/m16.jpg")));
            } else {
                lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            }
            break;
            case 2:
            hilo.suspend();
            suspendido = true;
            //String tiempo = txtTiempos.getText();
            //String nuevo = con + ".     " + lbltiempo.getText();
            //txtTiempos.setText(nuevo + "\n" + tiempo);
            con++;

            //----
            suspendido = true;
            seg = 0;
            min = 0;
            hora = 0;
            deci = 0;
            con = 1;
            lbltiempo.setText("00:00:00:00");
            lblCompleto.setIcon(new ImageIcon(getClass().getResource("/imagenes/sombrerero.png")));
            tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/s1.png")));
            tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/s2.png")));
            tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/s3.png")));
            tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/s4.png")));
            tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/s5.png")));
            tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/s6.png")));
            tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/s7.png")));
            tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/s8.png")));
            tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/s9.png")));
            tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/s10.png")));
            tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/s11.png")));
            tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/s12.png")));
            tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/s13.png")));
            tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/s14.png")));
            tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/s15.png")));
            if (tipo == 0) {
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/s16.png")));
            } else {
                lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            }
            break;
            case 3:
            hilo.suspend();
            suspendido = true;
            //String tiempo = txtTiempos.getText();
            //String nuevo = con + ".     " + lbltiempo.getText();
            //txtTiempos.setText(nuevo + "\n" + tiempo);
            con++;

            //----
            suspendido = true;
            seg = 0;
            min = 0;
            hora = 0;
            deci = 0;
            con = 1;
            lbltiempo.setText("00:00:00:00");
            lblCompleto.setIcon(new ImageIcon(getClass().getResource("/imagenes/pasayo.png")));
            tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/p1.jpg")));
            tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/p2.jpg")));
            tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/p3.jpg")));
            tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/p4.jpg")));
            tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/p5.jpg")));
            tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/p6.jpg")));
            tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/p7.jpg")));
            tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/p8.jpg")));
            tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/p9.jpg")));
            tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/p10.jpg")));
            tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/p11.jpg")));
            tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/p12.jpg")));
            tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/p13.jpg")));
            tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/p14.jpg")));
            tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/p15.jpg")));
            if (tipo == 0) {
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/p16.jpg")));
            } else {
                lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            }
            break;
            case 4:
            hilo.suspend();
            suspendido = true;
            //String tiempo = txtTiempos.getText();
            //String nuevo = con + ".     " + lbltiempo.getText();
            //txtTiempos.setText(nuevo + "\n" + tiempo);
            con++;

            //----
            suspendido = true;
            seg = 0;
            min = 0;
            hora = 0;
            deci = 0;
            con = 1;
            lbltiempo.setText("00:00:00:00");
            lblCompleto.setIcon(new ImageIcon(getClass().getResource("/imagenes/favoritos.png")));
            tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/f1.jpg")));
            tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/f2.jpg")));
            tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/f3.jpg")));
            tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/f4.jpg")));
            tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/f5.jpg")));
            tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/f6.jpg")));
            tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/f7.jpg")));
            tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/f8.jpg")));
            tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/f9.jpg")));
            tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/f10.jpg")));
            tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/f11.jpg")));
            tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/f12.jpg")));
            tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/f13.jpg")));
            tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/f14.jpg")));
            tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/f15.jpg")));
            if (tipo == 0) {
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/f16.jpg")));
            } else {
                lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            }
            break;
            case 5:
            hilo.suspend();
            suspendido = true;
            //String tiempo = txtTiempos.getText();
            //String nuevo = con + ".     " + lbltiempo.getText();
            //txtTiempos.setText(nuevo + "\n" + tiempo);
            con++;

            //----
            suspendido = true;
            seg = 0;
            min = 0;
            hora = 0;
            deci = 0;
            con = 1;
            lbltiempo.setText("00:00:00:00");
            tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/n1.png")));
            tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/n2.png")));
            tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/n3.png")));
            tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/n4.png")));
            tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/n5.png")));
            tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/n6.png")));
            tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/n7.png")));
            tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/n8.png")));
            tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/n9.png")));
            tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/n10.png")));
            tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/n11.png")));
            tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/n12.png")));
            tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/n13.png")));
            tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/n14.png")));
            tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/n15.png")));
            if (tipo == 0) {
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/n16.png")));
            } else {
                lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            }
            break;
        }
    }//GEN-LAST:event_cmbImagenesActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
        /**
        * Inicia el tiempo.
        */
        Random r1 = new Random();
        int x;
        if (tipo == 0) {
            if (!suspendido) {
                hilo.start();
                suspendido = true;
            } else {
                hilo.resume();
            }
            for (int i = 1; i < 100; i++) {
                x = r1.nextInt(16);
                seleccionar(x);
            }
        } else if (tipo == 1) {
            for (int i = 1; i <= 1000; i++) {
                x = r1.nextInt(16);
                mover(x);
            }
            if (!suspendido) {
                hilo.start();
                suspendido = true;
            } else {
                hilo.resume();
            }
        }
        banInicio = true;
    }//GEN-LAST:event_btnIniciarActionPerformed

     private boolean esValidoMov(int pos) {
        boolean salida = false;
        int dx;//fila disponible
        int dy;//
        int posx;
        int posy;
        dx = disponible / 4;
        dy = disponible % 4;
        posx = pos / 4;
        posy = pos % 4;
        if (dx == posx) {
            if (Math.abs(disponible - pos) == 1) {
                salida = true;
            }
        }
        if (dy == posy) {
            if (Math.abs(disponible - pos) == 4) {
                salida = true;
            }
        }
        return salida;
    }

    private void seleccionar(int pos) {

        if (!banClick) { // Primer clic
            pos1 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 2));
            banClick = true;
        } else {
            pos2 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
            banClick = false;
            //Intercambia imagenes de las posiciones pos1 y pos2
            intercambiar(pos1, pos2);
        }
    }

    private void intercambiar(int pos1, int pos2) {
        JLabel lblTemp = new JLabel();
        lblTemp.setIcon(tablero[pos1].getIcon());
        tablero[pos1].setIcon(tablero[pos2].getIcon());
        tablero[pos2].setIcon(lblTemp.getIcon());
        int tempo;
        tempo = datos[pos1];
        datos[pos1] = datos[pos2];
        datos[pos2] = tempo;
    }

    private void revisar() {
        if (banInicio && !banClick && verificar()) {
            JOptionPane.showMessageDialog(this, "Ya ganaste! ");
            hilo.suspend();
            suspendido = true;
            // String tiempo=txtTiempos.getText();
            String nuevo = con + ".     " + lbltiempo.getText();
            // txtTiempos.setText(nuevo+"\n"+tiempo);
            con++;
            //banPlay=false;
            cmbTipo.setSelectedIndex(0);
            tipo = 0;
            this.cmbImagenesActionPerformed(null);
            for (int i = 0; i < 16; i++) {
                tablero[i].setBorder(null);
            }
            banInicio = false;      //<--------------
        }
    }

    private void moverLinea(int pos) {
        if (banInicio) {
//            if (tipo==2) {
//                lblTablero.setIcon(tablero[0].getIcon());
//            }
        }
        if (pos / 4 == disponible / 4) {
            if (pos > disponible) {
                for (int i = disponible + 1; i <= pos; i++) {
                    mover(i);
                }
            } else {
                for (int i = disponible - 1; i >= pos; i--) {
                    mover(i);
                }
            }
        } else if (pos % 4 == disponible % 4) {
            if (pos > disponible) {
                for (int i = disponible + 4; i <= pos; i = i + 4) {
                    mover(i);
                }
            } else {
                for (int i = disponible - 4; i >= pos; i = i - 4) {
                    mover(i);
                }
            }
        }
//        if (tipo==2) {
//            tablero[12].setIcon(lblTempo);
//        }
    }

    /**
     * verificar si ya ganó, es decir si el rompecabezas ya esta armado
     * correctamente.
     *
     * @return true= ya ganó; false = no ganó
     */
    private boolean verificar() {
        for (int i = 0; i < 16; i++) {
            if (datos[i] != i) {
                return false;
            }
        }
        return true;
    }

    private void mover(int pos) {
        if (banInicio) {
            if (tipo == 0) {
                seleccionar(pos);
            } else if (tipo == 1) {
                if (esValidoMov(pos)) {
                    intercambiar(pos, disponible);
                    disponible = pos;
                }
            }
        }
    }

    public void tirar(int pos) {
        if (tipo == 0) {
            mover(pos);
        } else if (tipo == 1) {
            moverLinea(pos);
        }
        revisar();
    }
    Thread hilo = new Thread() {
        public void run() {
            try {
                while (true) {
                    if (deci > 99) {
                        deci = 0;
                        seg++;
                    }
                    if (seg > 59) {
                        seg = 0;
                        min++;
                    }
                    if (min > 59) {
                        min = 0;
                        hora++;
                    }
                    String s = "", m = "", h = "", d = "";
                    if (seg < 10) {
                        s = "0" + seg;
                    } else {
                        s = "" + seg;
                    }
                    if (min < 10) {
                        m = "0" + min;
                    } else {
                        m = "" + min;
                    }
                    if (hora < 10) {
                        h = "0" + hora;
                    } else {
                        h = "" + hora;
                    }
                    if (deci < 10) {
                        d = "0" + deci;
                    } else {
                        d = "" + deci;
                    }
                    deci++;
                    hilo.sleep(9);
                    lbltiempo.setText(h + ":" + m + ":" + s + ":" + d);
                }
            } catch (InterruptedException ie) {
                JOptionPane.showMessageDialog(rootPane, ie.getMessage());
            }
        }
    };

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:

        tipo = cmbTipo.getSelectedIndex();
        if (tipo == 0) { //Libre
            if (!suspendido) {
                hilo.start();
                suspendido = true;
            } else {
                hilo.resume();
            }
        } else if (tipo == 1) { //Clasico
            if (!suspendido) {
                hilo.start();
                suspendido = true;
            } else {
                hilo.resume();
            }
            lblImagen16.setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
            disponible = 15;

        }
        this.cmbImagenesActionPerformed(null);
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        tablero[0] = lblImagen01;
        tablero[1] = lblImagen02;
        tablero[2] = lblImagen03;
        tablero[3] = lblImagen04;
        tablero[4] = lblImagen05;
        tablero[5] = lblImagen06;
        tablero[6] = lblImagen07;
        tablero[7] = lblImagen08;
        tablero[8] = lblImagen09;
        tablero[9] = lblImagen10;
        tablero[10] = lblImagen11;
        tablero[11] = lblImagen12;
        tablero[12] = lblImagen13;
        tablero[13] = lblImagen14;
        tablero[14] = lblImagen15;
        tablero[15] = lblImagen16;
        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }
    }//GEN-LAST:event_formInternalFrameActivated

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
        // TODO add your handling code here:
     
    }//GEN-LAST:event_jPanel1FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox<String> cmbImagenes;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCompleto;
    private javax.swing.JLabel lblImagen01;
    private javax.swing.JLabel lblImagen02;
    private javax.swing.JLabel lblImagen03;
    private javax.swing.JLabel lblImagen04;
    private javax.swing.JLabel lblImagen05;
    private javax.swing.JLabel lblImagen06;
    private javax.swing.JLabel lblImagen07;
    private javax.swing.JLabel lblImagen08;
    private javax.swing.JLabel lblImagen09;
    private javax.swing.JLabel lblImagen10;
    private javax.swing.JLabel lblImagen11;
    private javax.swing.JLabel lblImagen12;
    private javax.swing.JLabel lblImagen13;
    private javax.swing.JLabel lblImagen14;
    private javax.swing.JLabel lblImagen15;
    private javax.swing.JLabel lblImagen16;
    private javax.swing.JLabel lbltiempo;
    // End of variables declaration//GEN-END:variables
}
